---
  title: "Effects of speech manipulations on warmth (ANOVA)"
author: "Laura Fernández Gallardo"
date: "April 2018"
output: 
  github_document:
  toc: true
toc_depth: 3
---
  
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(root.dir = './')
knitr::opts_chunk$set(fig.width=5, fig.height=5, dpi=150)
```


```{r echo=FALSE}

# clear
rm(list=ls())

```

```{r message=FALSE, warning=FALSE}

# Libraries needed:

library(ggplot2) # for plots
library(ez) # for ezANOVA
library(data.table) # for dt significance
library(knitr) # for kable
library(xtable) # for table for LaTeX

``` 


## Objectives

To assess the effects of manipulated speech (pitch, pitch range and formant shifts) on speakers' attributed warmth.

Load all stimuli dataframe and listeners' answers from test.

```{r echo=FALSE} 

# setting paths and loading data
setwd("D:/Users/fernandez.laura/Documents/Work/Projects_Github/Speaker_Characteristics_Of_Manipulated_Speech/analysis")

all_stimuli <- read.csv(paste0("../listening_test/all_stimuli.csv"))

```

Load output generated by GUI (listeners' answers)

```{r}

path_testoutput <- "../listening_test/GUI/files/output" 

answers <- data.frame()
file.names <- dir(path_testoutput, pattern =".csv") 
for(i in 1:length(file.names)){
  dataread <- read.csv(paste0(path_testoutput,'/',file.names[i]), header=TRUE, sep=",") 
  answers <- rbind(answers,dataread)
}

```

Merge answers and all_stimuli (information of conditions)

```{r}

mydata <- merge(all_stimuli, answers)
summary(mydata)

```






